/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import javafx.application.Application;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import gradle.config.DbConnect;

public class App extends Application{

    @Override
    public void start(Stage primaryStage) throws Exception {
        TextField email = new TextField();
        TextField pass = new TextField();
        DbConnect dbConnect = new DbConnect();
        // dbConnect.getConnection();
    }
    
    public static void main(String[] args) {
        launch();
    }
}
