/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;
import javafx.geometry.Insets;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage stage) {
        Label ervin = new Label("Macbook lu M berapa boss?");
        Label l = new Label("Hello Ervinn");
        ervin.setStyle("-fx-font-size: 20px; -fx-text-fill: #333; -fx-font-weight: bold;");
        l.setStyle("-fx-font-size: 20px; -fx-text-fill: #333; -fx-font-weight: bold;");

        VBox vBox = new VBox();
        vBox.setSpacing(20);
        vBox.setPadding(new Insets(50));
        vBox.getChildren().addAll(ervin, l);

        Scene scene = new Scene(new StackPane(vBox), 640, 480);
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }

}
