// /*
//  * This Java source file was generated by the Gradle 'init' task.
//  */
// package gradle;

// import javafx.application.Application;
// import javafx.geometry.Pos;
// import javafx.scene.Scene;
// import javafx.scene.control.Button;
// import javafx.scene.control.TextField;
// import javafx.scene.layout.StackPane;
// import javafx.scene.layout.VBox;
// import javafx.stage.Stage;

// public class App extends Application{

//     @Override
//     public void start(Stage primaryStage) throws Exception {
//         // Membuat field untuk email dan password
//         TextField email = new TextField();
//         email.setPromptText("Email");
//         TextField pass = new TextField();
//         pass.setPromptText("Password");

//         // Membuat tombol untuk login dan sign up
//         Button loginBtn = new Button("Log In");
//         Button signupBtn = new Button("Sign Up");

//         // Membuat VBox dan menambahkan komponen
//         VBox containerField = new VBox(10); // 10 adalah spacing antar komponen
//         containerField.getChildren().addAll(email, pass, loginBtn, signupBtn);
//         containerField.setAlignment(Pos.CENTER); // Menyetel posisi VBox di tengah

//         // Membuat StackPane untuk mengatur posisi VBox di tengah layar
//         StackPane root = new StackPane();
//         root.getChildren().add(containerField);
//         StackPane.setAlignment(containerField, Pos.CENTER);

//         // Menyetel scene dan stage
//         Scene scene = new Scene(root, 300, 250); // Ukuran window
//         primaryStage.setTitle("Login Page");
//         primaryStage.setScene(scene);
//         primaryStage.show();
//     }
    
//     public static void main(String[] args) {
//         launch();
//     }
// }
